#!/bin/sh -e

#CONFIGFILE=/etc/dynamic-ip/dynamic-ip.cfg
#set -e

# Source debconf library.
. /usr/share/debconf/confmodule


 # Carga el fichero de configuracion, si existe.
 #        if [ -e $CONFIGFILE ]; then
 #           . $CONFIGFILE || true

#                db_set dynamic-ip/UserName "$username"
# 	        db_get dynamic-ip/Password "$password"
# 		db_get dynamic-ip/SMTP     "$smtp"
# 		db_get dynamic-ip/SMPTPort "$port"
  #      fi


# Configurar
#db_input medium dynamic-ip/Basic_Config || true
db_input high dynamic-ip/Basic_Config
db_go

# Check their answer.
db_get dynamic-ip/Basic_Config

if [ "$RET" = "true" ]; then
  {
    db_input high  dynamic-ip/UserName || Username
    db_input high dynamic-ip/Password || Password
    db_input high  dynamic-ip/SMTP || true
    db_input high  dynamic-ip/SMPTPort || true
    db_go
  }
else
{
  db_purge
}
fi


exit 0
