#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Configurar
#db_input medium dynamic-ip/Basic_Config || true
db_input high dynamic-ip/Basic_Config
db_go

# Check their answer.
db_get dynamic-ip/Basic_Config

if [ "$RET" = "true" ]; then
  {
    db_input high  dynamic-ip/UserName || Username
    db_input high dynamic-ip/Password || Password
    db_input high  dynamic-ip/SMTP || true
    db_input high  dynamic-ip/SMPTPort || true
    db_go
  }
else
{
  db_purge
}
fi


exit 0
