#!/bin/sh -e

#CONFIGFILE=/etc/dynamic-ip/dynamic-ip.cfg
#set -e

# Source debconf library.
. /usr/share/debconf/confmodule


# Configurar
db_input high dynamic-ip/Basic_Config
db_go

# Check their answer.
db_get dynamic-ip/Basic_Config

if [ "$RET" = "true" ]; then
  {
    db_input high  dynamic-ip/UserName || Username
    db_input high dynamic-ip/Password || Password
    db_input high  dynamic-ip/SMTP || SMTP
    db_input high  dynamic-ip/SMPTPort || SMTPPort
    db_go
  }
fi

exit 0
